/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.java.project;


import java.util.Random;
import javax.naming.Context;
import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
/**
 *
 * @author Salama
 */
public class GeneratePassword extends javax.swing.JFrame {

    /**
     * Creates new form GeneratePassword
     */
    private String password = "";
    public GeneratePassword() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        generateBtn = new javax.swing.JButton();
        warningLbl = new javax.swing.JLabel();
        copyBtn = new javax.swing.JButton();
        coppyLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        choice1 = new javax.swing.JRadioButton();
        choice2 = new javax.swing.JRadioButton();
        choice3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 26, 60));

        generateBtn.setBackground(new java.awt.Color(204, 204, 204));
        generateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generateBtn.setForeground(new java.awt.Color(41, 26, 60));
        generateBtn.setText("Generate Password");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        warningLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        warningLbl.setForeground(new java.awt.Color(0, 102, 0));
        warningLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLbl.setToolTipText("");

        copyBtn.setBackground(new java.awt.Color(255, 255, 255));
        copyBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        copyBtn.setForeground(new java.awt.Color(41, 26, 60));
        copyBtn.setText("Copy Password");
        copyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyBtnActionPerformed(evt);
            }
        });

        coppyLbl.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        coppyLbl.setForeground(new java.awt.Color(255, 255, 255));
        coppyLbl.setToolTipText("");

        backBtn.setBackground(new java.awt.Color(204, 204, 204));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        backBtn.setForeground(new java.awt.Color(41, 26, 60));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        choice1.setBackground(new java.awt.Color(41, 26, 60));
        choice1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        choice1.setForeground(new java.awt.Color(255, 255, 255));
        choice1.setText("Allow Characters");

        choice2.setBackground(new java.awt.Color(41, 26, 60));
        choice2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        choice2.setForeground(new java.awt.Color(255, 255, 255));
        choice2.setText("Allow Numbers");
        choice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice2ActionPerformed(evt);
            }
        });

        choice3.setBackground(new java.awt.Color(41, 26, 60));
        choice3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        choice3.setForeground(new java.awt.Color(255, 255, 255));
        choice3.setText("Add Special Letter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(warningLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(copyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coppyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 76, Short.MAX_VALUE))
                            .addComponent(choice3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(choice2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(choice3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(warningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(copyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(coppyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MainPage mp = new MainPage();
        mp.show();
        mp.setLocationRelativeTo(null);
        mp.setResizable(false);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void copyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyBtnActionPerformed
        // TODO add your handling code here:
        if(password.equals("") || warningLbl.getText().equals(("Password should include at least Numbers or characters")))
        {
            coppyLbl.setText("U should generate password first");
            coppyLbl.setForeground(new java.awt.Color(255, 0, 0));
        }
        else
        {
            StringSelection stringSelection = new StringSelection(password);
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            clipboard.setContents(stringSelection, null);
            coppyLbl.setText("Password Coppied to clipboard");
            coppyLbl.setForeground(new java.awt.Color(0, 255, 0));
        }

    }//GEN-LAST:event_copyBtnActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        // TODO add your handling code here:
        if(choice1.isSelected()|| choice2.isSelected())
        {
            String Name[] = new String[]{
            "Cyan","Flax","Hound","Owl","Sephia","Opal","Viper","Dragon","Lilac","Chawk","Rust","Rock","Silent","Storm","Neon","Elk","Beige","Weight","Blue","Roc","Hero"
            ,"Jade", "Stag","Pearl","Shark","Ruby","Grell","Onyx","Imp","Grumpy","Kitten","Flame","Rhino","Lava","Kodo","Brown","Tank","Elekk","Azure","Lich","Lime","Satyr"
            ,"Luffy","Zoro","Sanji","Usopp","Roben","Nami","Frankey","Chopper","Onyx","Stentric","Caboose","Ebon","Gnoll","Olive","Badger","Bear","Inkey","Thief","Flame","Ogre",
            "Loa","Whale","Drake","Law","Gold","Silver","Bronze","Big","Street","Vane","Vien","Venom","Lion","Elephant","Dodge","Kneel","Strange","Strike","Stage","Steal","Stonck",
            "Chock","Strock","Block","Dash","Dang","Bang","Style","Sting","Super","Ninja","Hook","Hawk","Stream","Sniper","Stone","Keeper","Pharah","Pharoh","Sphenix","Point","Jungle"
            ,"Prime","Pipe","Dream","Music","Theme","Bleam","Slime","Climb","Cream","Cheese","Scheme","Flee","Argue","Creak","Assasin","Black","Flag","Ball","Straw","Hats","Bats","Chat"
            ,"Bungle","Stungle","Streak","Speak","Chart","Astro","Goku","Son","Crop","Abandon","Ability","Able","Academy","Actual","Barrier","Address","Adjust","Admire","Advance","Admit"
            ,"Bigasos","Afford","Agenda","Lake","Mealy","Elias","Aid","Alience","Kaizoku","Clover","Gate","Bait","State","Strake","Stieve","Steal","Believe","Blood","Blow","Blind","Boom","Border"
            ,"Boundry","Beneath","Day","Come","Around","Season","Stop","Hide","Ground","Sky","Scream","Heart","Beat","Hold","Innocence","Right","Wrong","Demon","Angle","Brave","Butter","Cabient","Cable"
            ,"Stable","Natural","Light","Dark","Trees","Shadow","Past","Glass","Youth","Beast","Piece","Truth","Price","Pay","Leave","Ache","Cast","Away","Product","Hunter","Pray","Age","Fade","Oath"
            ,"Blood","Break","Taste","Upon","Thunder","Lightning","Shattered","Desert","Teaser","Teal","Chair","Care","Flare","Snail","Scale","Agile","Mobile","Style","Hostage","Montage","Tream","Game"
            ,"Hunger","Trick","Chick","Stick","Stuck","Hard","Stang","Easy","Stressed","Jungle","Sneeze","Stealth","Spread","Ease","Flare","Bream",
        };
        password = "";
        String[] Special = new String[] {
          "!","@","#","$","%","^","&","*","-","_","+"  
        };
        String[] Number = new String[]{
       
             "1","2","3","4","5","6","7","8","9","0"
        };
        Random rand = new Random();
        int upperbound = Name.length;
        int idx = rand.nextInt(upperbound);
        String FirstName = Name[idx];
        idx = rand.nextInt(upperbound);
        String SecondName = Name[idx];
        while(SecondName.equals(FirstName))
        {
           SecondName = Name[rand.nextInt(upperbound)]; 
        }
       
        String Num = "";
        
        upperbound = 10;
        int times = 3;
        if(!choice1.isSelected())
        {
            times = 10;
        }
        for(int i = 0; i < times; i++)
        {
            Num += Number[rand.nextInt(upperbound)];
        }
        String S;
        upperbound = Special.length;
        S = Special[rand.nextInt(upperbound)];
        if(choice1.isSelected())
        {
           password += FirstName;
        }
        if(choice3.isSelected())
        {
            password += S;
        }
        if(choice1.isSelected())
        {
            password += SecondName;
        }
        if(choice2.isSelected())
        {
            password += Num;
        }
            
        warningLbl.setText("Your Password is: " + password);
        warningLbl.setForeground(new java.awt.Color(255,255,255));
        
        }
        else
        {
            warningLbl.setText("Password should include at least Numbers or characters");
            warningLbl.setForeground(new java.awt.Color(255, 0, 0));
        }
        
        coppyLbl.setText("");
    }//GEN-LAST:event_generateBtnActionPerformed

    private void choice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choice2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GeneratePassword gp = new GeneratePassword();
                gp.setVisible(true);
                gp.setLocationRelativeTo(null);
                gp.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton choice1;
    private javax.swing.JRadioButton choice2;
    private javax.swing.JRadioButton choice3;
    private javax.swing.JLabel coppyLbl;
    private javax.swing.JButton copyBtn;
    private javax.swing.JButton generateBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel warningLbl;
    // End of variables declaration//GEN-END:variables
}
